pipeline {
    agent { label 'docker' }
    triggers { pollSCM('* * * * *') }
    stages {
        stage('Cloning_the_git') {
            steps {
                git branch: 'main',
                       url: 'https://github.com/maheshryali123/poojastores.git'
            }
        }
        stage('Copy_the_code') {
            steps {
                sh """
                cp -r /home/ubuntu/remote_repo/workspace/poojastore/ppojastores/trunk/PoojaStores/* /home/ubuntu/mahesh
                """
            }
        }
        stage('Build_the_code') {
            steps {
                sh """
                /home/ubuntu/dotnet build /home/ubuntu/mahesh/PoojaStores.csproj
                """
            }    
        }
        stage('Build_the_Docker_image') {
            steps {
                sh """
                docker image build -t poojastoresnew:1.0 .
                docker image tag poojastoresnew:1.0 maheshryali/poojastoresnew:1.0
                docker image push maheshryali/poojastoresnew:1.0
                """
            }
        }
    }
}