pipeline {
    agent { label 'PROJECT' }
    triggers { pollSCM('* * * * *')}
    stages {
        stage('Clone the code') {
            steps {
                git branch: 'main',
                       url: 'https://github.com/maheshryali123/poojastores.git'
            }    
        }
        stage('Copy_the_code') {
            steps {
                sh """
                mkdir PoojaStores
                cp -r /home/ubuntu/remote_repo/workspace/poojastores/ppojastores/trunk/PoojaStores /home/ubuntu/remote_repo/workspace/poojastores/PoojaStores
                """
            }
        }
    }
}